### ISSUE TITLE
Docker/Traefik Errors

### ISSUE THREAD

**Issue by mattlathrop** [shlinkio/shlink-web-client#358] opened 2020-12-20 23:37 UTC
#### Shlink web client version

* Version: 2.6.2
* How do you use shlink-web-client: Docker

#### Summary

I am trying to use the docker container of shlink to serve redirects from behind traefik reverse proxy. I seem to be having two issues both of which prevent me from using the web client (either the free hosted version or a self hosted copy). The docker container on 8080 seems to only respond to HTTP (not HTTPS) requests. This is find for traefik as it provides a layer on top that secures the connection. However when I do this and try to connect to the server from the web-client I get an error:
`response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I have the server setup such that the shlink is on lk.my.domain and the web client is on link.my.domain. I've also tried connecting the web-client directly to the exposed port (8086 in my case as I specify that in the docker compose file) but then I get either can't connect errors if I try over https or Mixed Content errors if I specify http. I don't really want to change my browser security settings to allow the Mixed Content so I would like to be able to either:

1. Set the docker container to server https over 8080 (or some other port)
2. Fix the Header error I am getting due to CORS policy

Any help is appreciated! It is worth noting redirects created via the CLI work fine and I can access the REST API via the browser/postman fine.

**Comment by acelaya** [comment] 2020-12-21 17:58
> response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

This is most probably caused by traefik not forwarding the CORS headers that shlink generates.

Without those headers, the browser doesn't trust the server when it's on a different domain, so you need to make sure traefik forwards those headers transparently.

Ideally, traefik should not filter out any header that shlink generates.

> The docker container on 8080 seems to only respond to HTTP (not HTTPS)

Yes, that's the expected behavior. Handling https is a responsibility outside of shlink's scope, so the recommended behavior is to have it behind a reverse proxy, as you are already doing.

> Mixed Content errors if I specify http

That happens with recent Google Chrome versions when trying to access shlink over HTTP from a web client served over HTTPS, as they consider it insecure.

Best option is to use https for everything. Solving the first problem with the CORS headers will solve this problem.

**Comment by acelaya** [comment] 2020-12-23 13:00
Yesterday I published a new version of the website which documents how to troubleshoot some of the most frequently issues, including the ones described here https://shlink.io/documentation/troubleshooting/#response-to-preflight-request-doesn't-pass-access-control-check:-no-'access-control-allow-origin'-header-is-present

Closing this as resolved.

**Closed as completed by acelaya** 2020-12-23 13:00 UTC
Labels: question, troubleshooting
