### ISSUE TITLE
domain dropdown stays disabled when using the latest docker image (server and webui)

### ISSUE THREAD

**Issue by mretich** [shlinkio/shlink-web-client#176] opened 2019-12-09 14:50 UTC
Hello,
I encountered following problem:

When I use the latest docker images (web-client 2.2.2 / Server: 1.20.2) the dropdown for the
domain stays disabled.
What I figured out is, that you're looking for a server version > 1.19 in the client, but the server
(at least in docker) returns a version "evelop".
`{"status":"pass","version":"evelop","links":{"about":"https://shlink.io","project":"https://github.com/shlinkio/shlink"}}`

Regards,
Michael Retich

**Comment by acelaya** [comment] 2019-12-09 16:04
Yep. That's a regression due to a recent change.

I would recommend using a specific version as a temporary workaround. Those will return the proper version number.

**Comment by mretich** [comment] 2019-12-09 16:10
Hi, thanks!
I have tried it with a specific version, this works as expected.

**Comment by acelaya** [comment] 2019-12-09 16:14
Good to hear :)

I will close this ticket and open another one on shlink repo, since the big is actually there.

**Closed as completed by acelaya** 2019-12-09 16:14 UTC
Labels: question

**Comment by acelaya** [comment] 2019-12-09 21:38
@mretich the fix has been merged and the `latest` docker tag now properly returns `latest` as the version constraint, which will make the web client to properly enable the latest features.

**Comment by mretich** [comment] 2019-12-10 07:34
@acelaya thanks, I will try it out and give you feedback on this.

**Comment by mretich** [comment] 2019-12-10 07:37
@acelaya:

It now works as expected.
Thanks a lot for the fast bugfix!
