### ISSUE TITLE
Export Servers

### ISSUE THREAD

**Issue by yodaphone** [shlinkio/shlink-web-client#1034] opened 2024-01-20 23:14 UTC
### Shlink version

3.7.3

### PHP version

8.3 (running via docker image, latest)

### How do you serve Shlink

RoadRunner Docker image

### Database engine

MySQL

### Database version

10.10.4

### Current behavior

 The export server button on Manage Servers page puts out a blank csv file. the headings are also wrong. they are the same as the export URLs even though the file names are different.
[shlink-servers.csv](https://github.com/shlinkio/shlink/files/13999461/shlink-servers.csv)
 
I'm use the hosted shlink client via app.shlink.io

### Expected behavior

 the exported CSV must show the list of servers but its blank

### How to reproduce

 just add a few servers and click on export button

**Comment by acelaya** [comment] 2024-01-21 10:51
I have managed to reproduce it the other way around. If you first export servers and then try to export short URLs, it happens the same, you end up with an empty file which has the server headers instead of the short URL ones.

This makes me think there's some kind of unintended stastefulness in the service which generates CSVs.

However, I cannot reproduce it in `develop`, because the app has suffered deep architectural changes there. Among other things, everything related with short URLs per se now lives on a [different component](https://github.com/shlinkio/shlink-web-component), which handles its own CSV generation logic independent with the servers one which still lives in this repo.

I'll close this as solved, as it will be included in upcoming shlink-web-client 4.0.0, but I'll keep an eye on it, as introducing CSV exporting somewhere else could let us to the same issue.

**Closed as completed by acelaya** 2024-01-21 10:51 UTC
Labels: bug
