### ISSUE TITLE
Import from file not working (Windows 10 Pro)

### ISSUE THREAD

**Issue by cyb3rko** [shlinkio/shlink-web-client#480] opened 2021-09-04 16:30 UTC
#### Shlink web client version

* Version: 3.2.0
* How do you use shlink-web-client: app.shlink.io

#### Summary

If I try to import one / several servers from a file it gives the error:
"The servers could not be imported. Make sure the format is correct."

It's a file exported today so it's not outdated and formatted correctly.
On iMac importing from this file works.

#### Current behavior

Importing form file is not working on Windows 10.

#### Expected behavior

It should work :)

#### How to reproduce

Click "Add a server" on home page.
Click "Import from file".
Select the file on your pc.
The error occurs.

[shlink-servers.csv](https://github.com/shlinkio/shlink-web-client/files/7110468/shlink-servers.csv)

**Comment by acelaya** [comment] 2021-09-04 17:37
Can you share the file you are trying to upload? You can set fake URLs and API keys

**Comment by cyb3rko** [comment] 2021-09-04 20:30
Added it.

**Comment by acelaya** [comment] 2021-09-05 09:31
I have just imported your file as it is, using https://app.shlink.io, and it worked fine

I'll try to test from Windows, as I was on Linux.

Also, what browser are you using?

**Comment by acelaya** [comment] 2021-09-05 09:37
Yep, on windows, using either Google Chrome or Microsoft Edge, it throws the error.

I'll need to set-up a dev env in order to debug it, so it may take some time.

**Comment by cyb3rko** [comment] 2021-09-05 09:38
Okay, thanks for approving.
I tried Chrome and Edge on WIndows too, but did not try it out on Linux yet.
But if you already did, it should be fine.

**Comment by acelaya** [comment] 2021-09-05 14:20
I found the root cause.

The app is expecting provided file to have a `type` property with value `text/csv`, `text/comma-separated-values` or `application/csv`, but on Windows it resolves to an empty string on chromium-based browsers (with Firefox seems to work).

I guess I'll change the approach, and try to parse whatever file is provided, without checking the mime type, and then verify the result is a valid list of servers and no error is thrown in the process.

**Comment by cyb3rko** [comment] 2021-09-05 14:23
Perfect, thanks for investigating!

**Comment by acelaya** [comment] 2021-09-12 08:04
I have just merged the fix for this. Will be part of v3.2.1

**Closed as completed by acelaya** 2021-09-12 08:04 UTC
Labels: bug

**Comment by cyb3rko** [comment] 2021-09-12 08:26
Awesome, thanks!
